[base]
  publish = "build/"
  command = "npm run build"

[[headers]]
  # Define the path to the resource
  for = "/notes.json"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[build.environment]
  NODE_VERSION = "22"